name: Release Charts

on:
  push:
    branches:
      - gh-pages
    paths:
      - 'charts/**'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR_EMAIL"
        env:
          GITHUB_ACTOR: '${{ vars.GH_SYSTEMSDT_USERNAME }}'
          GITHUB_ACTOR_EMAIL: '${{ secrets.GH_SYSTEMSDT_EMAIL }}'
      - name: Run chart-releaser
        uses: helm/chart-releaser-action@main
        env:
          CR_TOKEN: '${{ secrets.GH_SYSTEMSDT_TOKEN }}'
